Added cfg/match_error|warning

diff --git a/recipies/library/BuildCfg b/recipies/library/BuildCfg
--- a/recipies/library/BuildCfg
+++ b/recipies/library/BuildCfg
@@ -4,4 +4,14 @@ build_cfg_file="$1"
 build_configs="$2"
 platform="$3"
 
-echo "\"$1\"  \"$2\"  \"$3\"  \"$4\""
+echo "# Processing: \"$1\"  \"$2\"  \"$3\"  \"$4\" / HDR"
+echo ">> some-command  / CMD"
+echo "This is some command output to stdout / SKIPPED"
+echo "This is some command output to stderr / SKIPPED" >&2
+echo ERROR: $1 made an error / ERR
+echo Some not standard fatal error that should be caught / ERR
+echo WARNING: $1 is suspicious / WRN
+echo Some lite error that should become a / WRN
+echo Some not standard lite error / SKIPPED
+# echo !!! ERROR: "\"$1\" error caught
+# echo !!! WARNING: "\"$1\" warning cought
